dist: focal
language: c

os: linux
arch: s390x
compiler: gcc

env:
    - CFLAGS="-O3 -Wextra -pedantic -Werror"
    - CONFIGURE_OPTS=""

matrix:
    include:
        - name: "linux-amd64-gcc"
          os: linux
          arch: amd64
          compiler: gcc
        - name: "linux-ppc64le-gcc"
          os: linux-ppc64le
          compiler: gcc
        - name: "linux-ppc64le-gcc"
          os: linux-ppc64le
          compiler: gcc
          env: CONFIGURE_OPTS="--with-cpu=no"
        - name: "linux-s390x-gcc"
          os: linux
          arch: s390x
          compiler: gcc
        - name: "linux-s390x-gcc-sw"
          os: linux
          arch: s390x
          compiler: gcc
          env: CONFIGURE_OPTS="--with-cpu=no"

script:
    - mkdir $(pwd)/install
    - ./configure --prefix=$(pwd)/install ${CONFIGURE_OPTS}
    - make
    - make install
    - make check
